version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-203-160-194.compute-1.amazonaws.com
            database: dvrl6placfmhv
            schema: public
            user: ltdgbnumuczwrq
            password: 014e25523a1b221dfe56af6b408a0b35d2744a35b422e2d0abe4ceb24e2b3ae7
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true